#region Licence
/****************************************************************
 *  Filename: UserErrors.cs
 *  ----------------------------------------------------------
 *  Author        Martin Meissner
 *  Date          2026-05-19
 *  Copyright (c) 2026 Martin Meissner.
 *                Released under the Apache License 2.0 as part of
 *                the open-source PlayOnDemand release.
 *
 *  SPDX-License-Identifier: Apache-2.0
 ****************************************************************/
#endregion
using System;
using System.Collections.Generic;
using System.Text;
// ReSharper disable InconsistentNaming

namespace Pod.Enums
{
    /// <summary>
    /// Error Codes
    /// </summary>
    public enum UserError
    {
        #region Generated by Entities
        /// <summary>
        /// General Error were error messages should not be leaked
        /// </summary>
        InternalError = 0,

        StationInvalidQrCode = 100,
        StationInvalidControlMode,
        StationInvalidDisplayName,
        StationInvalidUserId,
        StationInvalidStationId,
        StationNotFound,
        StationNoValidSubscription,
        StationPasswordTooShort,
        StationPasswordTooLong,
        StationPasswordHasNoDigits,
        StationPasswordHasNoSpecialChars,
        StationPasswordHasNotEnoughUniqueChars,
        StationPasswordHasNoUpperChars,
        StationPasswordHasNoLowerChars,

        OrderInvalidCurrencyCode = 200,
        OrderInvalidPaymentAmount,
        OrderInvalidDuration,
        OrderInvalidExpireDate,
        OrderCustomerPaymentReferenceHasWhiteSpace,
        OrderCustomerPaymentReferenceTooLong,
        OrderAlreadyPayed,
        OrderAlreadyExpired,
        OrderMaximumActiveAmountReached,

        ConnectionInvalidParameter = 300,
        ConnectionInvalidId,

        SessionInvalidTimeChange = 400,
        SessionCanNotBeStarted,
        SessionIsNotStarted,
        SessionRuleDurationInvalid,
        SessionNotFound,

        EMailAccountNameNotSet = 500,
        EMailAccountDataInvalid,
        EMailTemplateDataInvalid,
        EMailNoReceiverSet,
        EMailAddressInvalid,
        TemplateInvalidVariable,
        #endregion

        #region Generated by Server Services
        AdminInvalidUsername  = 1000,
        AdminRoleInvalid,
        AdminRoleNotFound,
        AdminUsernameNotFound,
        AdminRoleFailedToAdd,
        AdminRoleFailedToRemove,
        AdminUserDeleteError,

        ShellServerInvalidId = 1100,
        ShellServerInvalidDisplayName,
        ShellServerInvalidHostAddress,
        ShellServerInvalidPort,
        ShellServerInvalidInternalHostAddress,
        ShellServerInvalidInternalPort,
        ShellServerInvalidHeartbeatValue,
        ShellServerInvalidTimeoutValue,
        ShellServerNotFound,

        ShellClientInvalidStationId = 1200,
        ShellClientInvalidPassword,
        ShellClientRequestNull,
        ShellClientInvalidDeviceIdentity,
        ShellClientNoServerAvailable,
        ShellClientServerMismatch,
        ShellClientConnectionIdMismatch,
        ShellClientNetworkStateMismatch,
        ShellClientConnectionTimedOut,
        ShellClientOtherConnectionStillAlive,
        ShellClientOtherDeviceIdentityConnected,
        ShellClientSessionStatePreRequirementNotMeet,
        ShellClientGetLoginRequestTimeout,


        
        StationIsNotConnected = 1300,
        StationDidNotRespondInTime,
        StationErrorOccured,
        StationMaxAmountReached,
        StationPublicKeyInvalid,
        StationPublicKeyNotFound,

        ApplicationStationNotFound = 1400,
        ApplicationDeviceNotFound,
        ApplicationRootNotFound,
        ApplicationNotFound,
        ApplicationInvalidConnectionId,
        ApplicationInvalidSyncTimestamp,


        UserIdentityDefaultError = 1500,
        UserIdentityConcurrencyFailure,
        UserIdentityPasswordMismatch,
        UserIdentityInvalidToken,
        UserIdentityRecoveryCodeRedemptionFailed,
        UserIdentityLoginAlreadyAssociated,
        UserIdentityInvalidUserName,
        UserIdentityInvalidEmail,
        UserIdentityDuplicateUserName,
        UserIdentityDuplicateEmail,
        UserIdentityInvalidRoleName,
        UserIdentityDuplicateRoleName,
        UserIdentityUserAlreadyHasPassword,
        UserIdentityUserLockoutNotEnabled,
        UserIdentityUserAlreadyInRole,
        UserIdentityUserNotInRole,
        UserIdentityPasswordTooShort,
        UserIdentityPasswordRequiresUniqueChars,
        UserIdentityPasswordRequiresNonAlphanumeric,
        UserIdentityPasswordRequiresDigit,
        UserIdentityPasswordRequiresLower,
        UserIdentityPasswordRequiresUpper,
        UserIdentityInvalidEMailConfirmationCode,
        UserIdentityEMailUnconfirmed,
        UserInvalidPasswordRecoveryCode,

        UserIdentityInvalidRefreshToken,
        UserIdentityIsLockedOut,
        UserIdentityNotAllowedToLogin,
        UserIdentityInvalidId,

        UserAccountRegistrationUnavailable,

        EMailAccountNotFound= 2000,
        EmailTemplateNotFound,
        EMailAccountForTemplateNotFound,

        EmailSendFailure = 2100,
        #endregion

        #region Generated by Shell Client
        ShellClient_NotConnected,
        ShellClient_WasCanceled,
        #endregion

    }
}
