#region Licence
/****************************************************************
 *  Filename: StationCreateTests.cs
 *  ----------------------------------------------------------
 *  Author        Martin Meissner
 *  Date          2026-05-19
 *  Copyright (c) 2026 Martin Meissner.
 *                Released under the Apache License 2.0 as part of
 *                the open-source PlayOnDemand release.
 *
 *  SPDX-License-Identifier: Apache-2.0
 ****************************************************************/
#endregion
using System;
using FluentAssertions;
using Pod.Data;
using Pod.Data.Models.Shell;
using Pod.Data.Test.Fixtures;
using Xunit;

namespace Pod.Data.Test
{
    /// <summary>
    /// Characterization tests for <see cref="Station.Create"/>.
    /// These pin the entity-level invariants the rest of the system relies on
    /// so they survive the .NET 10 / EF Core 10 migration without behavioural drift.
    /// </summary>
    public class StationCreateTests
    {
        private static readonly Guid TestUserId = Guid.Parse("00000000-0000-0000-0000-000000000001");
        private const string DisplayName = "Test Station";
        private const string Password = "Strong-Password-1!";

        private static Station CreateValidStation()
        {
            var result = Station.Create(TestUserId, DisplayName, Password, new PasswordHasher());
            result.HasError().Should().BeFalse(string.Join("; ", result.ToErrorString()));
            return result.ReturnValue;
        }

        [Fact]
        public void Create_HappyPath_ReturnsStationWithAggregate()
        {
            var station = CreateValidStation();

            station.Should().NotBeNull();
            // station.Id is Guid.Empty until EF persists the entity (it's a private-set PK
            // assigned on SaveChanges). Don't assert on it here — DB-backed tests cover that.
            station.ApplicationUserId.Should().Be(TestUserId);
            station.StationSettings.Should().NotBeNull("settings auto-created with station");
            station.SubscriptionState.Should().NotBeNull("subscription state auto-created with station");
            station.ConnectionState.Should().NotBeNull("connection state auto-created with station");
            station.SessionDetails.Should().NotBeNull("session details auto-created with station");
            // ApiKeys is a private HashSet exposed as IReadOnlyCollection — null until first add.
            // Characterizing actual behaviour: the collection is null on a fresh Station before
            // CreateStationApiKey is called.
            (station.ApiKeys ?? (System.Collections.Generic.IReadOnlyCollection<Pod.Data.Models.Shell.StationApiKey>)new System.Collections.Generic.HashSet<Pod.Data.Models.Shell.StationApiKey>())
                .Should().BeEmpty("no api keys at creation time");
        }

        [Fact]
        public void Create_DisplayNameIsAppliedToStationSettings()
        {
            var station = CreateValidStation();
            station.StationSettings.DisplayName.Should().Be(DisplayName);
        }

        [Fact]
        public void Create_PasswordHashIsPopulated()
        {
            var station = CreateValidStation();
            station.VerifyPassword(Password, new PasswordHasher()).Should().BeTrue();
            station.VerifyPassword(Password + "x", new PasswordHasher()).Should().BeFalse();
        }

        [Fact]
        public void Create_EmptyUserId_Fails()
        {
            var result = Station.Create(Guid.Empty, DisplayName, Password, new PasswordHasher());
            result.HasError().Should().BeTrue();
        }

        [Fact]
        public void Create_EmptyDisplayName_Fails()
        {
            var result = Station.Create(TestUserId, string.Empty, Password, new PasswordHasher());
            result.HasError().Should().BeTrue();
        }

        [Fact]
        public void Create_NullPasswordHasher_Throws()
        {
            // Defensive: factory must not be invoked without a hasher.
            Action act = () => Station.Create(TestUserId, DisplayName, Password, null);
            act.Should().Throw<Exception>();
        }

        [Fact]
        public void CreateStationApiKey_AddsToStationsApiKeysWithUniqueSecrets()
        {
            // CreateStationApiKey enforces Station.Id != Guid.Empty AND _apiKeys non-null.
            // We persist + reload to satisfy both invariants. PublicKey (the EF-managed PK
            // on StationApiKey) stays Guid.Empty on the in-memory side because EF Core's
            // InMemory provider doesn't auto-generate Guid values - on real Postgres the DB
            // assigns it. The functional uniqueness this test cares about is SecretKey (32
            // random bytes generated by StationApiKey.Generate); PublicKey uniqueness is a
            // relational-DB concern covered by integration tests.
            using var db = InMemoryDbContextFactory.Create();
            var transient = CreateValidStation();
            db.Entry(transient).Property(nameof(Station.Id)).CurrentValue = Guid.NewGuid();
            db.Stations.Add(transient);
            db.SaveChanges();

            var station = db.Stations.Find(transient.Id);
            station.Should().NotBeNull();
            db.Entry(station).Collection(s => s.ApiKeys).Load();
            station.ApiKeys.Should().NotBeNull();

            var first = station.CreateStationApiKey("default");
            first.HasError().Should().BeFalse(string.Join("; ", first.ToErrorString()));

            var second = station.CreateStationApiKey("backup");
            second.HasError().Should().BeFalse(string.Join("; ", second.ToErrorString()));

            station.ApiKeys.Should().HaveCount(2);
            first.ReturnValue.SecretKey.Should().NotBe(second.ReturnValue.SecretKey);
            first.ReturnValue.SecretKey.Should().NotBeNullOrWhiteSpace();
            second.ReturnValue.SecretKey.Should().NotBeNullOrWhiteSpace();
        }
    }
}
