// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pod.Data;

#nullable disable

namespace Pod.Data.Migrations
{
    [DbContext(typeof(PodDbContext))]
    [Migration("20260516055939_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("SubscriptionOrder_OrderNumber_seq")
                .StartsAt(1000L);

            modelBuilder.HasSequence("User_CustomerNumber_seq")
                .StartsAt(100L);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Pod.Data.Models.Billing.SubscriptionChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExtendsFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExtendsToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SubscriptionPaymentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubscriptionStateId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPaymentId")
                        .IsUnique();

                    b.HasIndex("SubscriptionStateId");

                    b.ToTable("SubscriptionChanges");
                });

            modelBuilder.Entity("Pod.Data.Models.Billing.SubscriptionOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedFromIpAddress")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerOrderReference")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OrderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"SubscriptionOrder_OrderNumber_seq\"')");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("SubscriptionPaymentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubscriptionStateId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("TimeOrdered")
                        .HasColumnType("interval");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("SubscriptionPaymentId")
                        .IsUnique();

                    b.HasIndex("SubscriptionStateId");

                    b.ToTable("SubscriptionOrders");
                });

            modelBuilder.Entity("Pod.Data.Models.Billing.SubscriptionPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("PaymentGatewayReference")
                        .HasColumnType("text");

                    b.Property<DateTime>("PaymentReceivedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPayments");
                });

            modelBuilder.Entity("Pod.Data.Models.Mail.EMailAccountData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AuthMethod")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("SenderName")
                        .HasColumnType("text");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("integer");

                    b.Property<string>("SmtpServer")
                        .HasColumnType("text");

                    b.Property<bool>("UseSsl")
                        .HasColumnType("boolean");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EMailAccounts");
                });

            modelBuilder.Entity("Pod.Data.Models.Mail.EMailAccountDataEMailContentTemplate", b =>
                {
                    b.Property<Guid>("EMailAccountDataId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EMailContentTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("EMailAccountDataId", "EMailContentTemplateId");

                    b.HasIndex("EMailContentTemplateId");

                    b.ToTable("EmailAccTemplateLinks");
                });

            modelBuilder.Entity("Pod.Data.Models.Mail.EMailReceiver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text");

                    b.Property<Guid>("EmailSendOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmailSendOrderId");

                    b.ToTable("EMailReceiver");
                });

            modelBuilder.Entity("Pod.Data.Models.Mail.EMailVariableValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmailSendOrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Key")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmailSendOrderId");

                    b.ToTable("EMailVariableValue");
                });

            modelBuilder.Entity("Pod.Data.Models.Mail.EmailContentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHtml")
                        .HasColumnType("text");

                    b.Property<string>("ContentText")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<int>("Identifier")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectText")
                        .HasColumnType("text");

                    b.Property<char>("VariableControlChar")
                        .HasColumnType("character(1)");

                    b.HasKey("Id");

                    b.ToTable("EmailContentTemplates");
                });

            modelBuilder.Entity("Pod.Data.Models.Mail.EmailSendOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMsg")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSendAttemptUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SendAttempts")
                        .HasColumnType("bigint");

                    b.Property<int>("SendState")
                        .HasColumnType("integer");

                    b.Property<int>("TemplateIdentifier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SendState");

                    b.ToTable("EmailSendOrders");
                });

            modelBuilder.Entity("Pod.Data.Models.Mail.TemplateVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<Guid>("EmailContentTemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<int>("StartChar")
                        .HasColumnType("integer");

                    b.Property<int>("VariableKey")
                        .HasColumnType("integer");

                    b.Property<string>("VariableKeyString")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TemplateVariable");

                    b.HasDiscriminator<string>("Discriminator").HasValue("TemplateVariable");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Pod.Data.Models.Servers.ShellServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("ConnectTimeout")
                        .HasColumnType("interval");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("HeartbeatInterval")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HeartbeatTimeout")
                        .HasColumnType("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PublicHostAddress")
                        .HasColumnType("text");

                    b.Property<long>("PublicInterfaceVersion")
                        .HasColumnType("bigint");

                    b.Property<long>("PublicPort")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PublicHostAddress", "PublicPort")
                        .IsUnique();

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.ApplicationRoot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceIdentityId")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSyncTimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeviceIdentityId");

                    b.HasIndex("StationId", "DeviceIdentityId")
                        .IsUnique();

                    b.ToTable("ApplicationRoots");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.ChangeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<int>("RequestFrom")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceIpAddress")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("TimeChange")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("ChangeRequest");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.ClosedConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ClosedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ConnectedToServerOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceIdentityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DisconnectedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RequestedServerOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("DeviceIdentityId");

                    b.HasIndex("ServerId");

                    b.HasIndex("StationId");

                    b.ToTable("ClosedConnections");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.ConnectionState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConnectedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceIdentityId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastHeartbeatOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NetworkState")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ServerRequestOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ShellServerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DeviceIdentityId")
                        .IsUnique();

                    b.HasIndex("ShellServerId");

                    b.HasIndex("StationId")
                        .IsUnique();

                    b.ToTable("ConnectionStates");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.DeviceIdentity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DeviceIdentities");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.LocalApp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationRootId")
                        .HasColumnType("uuid");

                    b.Property<long>("InstanceVersion")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInstalled")
                        .HasColumnType("boolean");

                    b.Property<string>("LocalDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UniqueAppId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InstanceVersion");

                    b.HasIndex("UniqueAppId");

                    b.HasIndex("ApplicationRootId", "UniqueAppId")
                        .IsUnique();

                    b.ToTable("LocalApps");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<string>("RequestFromIpAddress")
                        .HasColumnType("text");

                    b.Property<string>("RequestReference")
                        .HasColumnType("text");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SendOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SendToConnectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SessionRuleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.Property<int>("StopReason")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StoppedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SessionRuleId")
                        .IsUnique();

                    b.HasIndex("StationId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.SessionDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("TimeoutLoginRequestDelivery")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("TimeoutLoginRequestResponse")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("UserTimeForLoginRequestResponse")
                        .HasColumnType("interval");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("StationId")
                        .IsUnique();

                    b.ToTable("SessionDetails");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.SessionRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StartApplication")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("StartDuration")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.ToTable("SessionRule");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.SessionRuleLocalApp", b =>
                {
                    b.Property<Guid>("SessionRuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocalAppId")
                        .HasColumnType("uuid");

                    b.HasKey("SessionRuleId", "LocalAppId");

                    b.HasIndex("LocalAppId");

                    b.ToTable("SessionRuleLocalApp");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.StationApiKey", b =>
                {
                    b.Property<Guid>("PublicKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("SecretKey")
                        .HasColumnType("text");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.HasKey("PublicKey");

                    b.HasIndex("StationId");

                    b.ToTable("StationApiKeys");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.StationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ControlMode")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("QRCode")
                        .HasColumnType("text");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("StationId")
                        .IsUnique();

                    b.ToTable("StationSettings");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.SubscriptionState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("StationId")
                        .IsUnique();

                    b.ToTable("SubscriptionStates");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.UniqueApp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatorId")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<int>("Origin")
                        .HasColumnType("integer");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UniqueApps");
                });

            modelBuilder.Entity("Pod.Data.Models.Users.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Pod.Data.Models.Users.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<long>("CustomerNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"User_CustomerNumber_seq\"')");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasMaxLength(256)
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerNumber")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Pod.Data.Models.Mail.EmailVariable", b =>
                {
                    b.HasBaseType("Pod.Data.Models.Mail.TemplateVariable");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasIndex("EmailContentTemplateId");

                    b.HasDiscriminator().HasValue("EmailVariable");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Pod.Data.Models.Users.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Pod.Data.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Pod.Data.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Pod.Data.Models.Users.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pod.Data.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Pod.Data.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pod.Data.Models.Billing.SubscriptionChange", b =>
                {
                    b.HasOne("Pod.Data.Models.Billing.SubscriptionPayment", "SubscriptionPayment")
                        .WithOne("SubscriptionChange")
                        .HasForeignKey("Pod.Data.Models.Billing.SubscriptionChange", "SubscriptionPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pod.Data.Models.Shell.SubscriptionState", "SubscriptionState")
                        .WithMany("SubscriptionChanges")
                        .HasForeignKey("SubscriptionStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPayment");

                    b.Navigation("SubscriptionState");
                });

            modelBuilder.Entity("Pod.Data.Models.Billing.SubscriptionOrder", b =>
                {
                    b.HasOne("Pod.Data.Models.Billing.SubscriptionPayment", "SubscriptionPayment")
                        .WithOne("SubscriptionOrder")
                        .HasForeignKey("Pod.Data.Models.Billing.SubscriptionOrder", "SubscriptionPaymentId");

                    b.HasOne("Pod.Data.Models.Shell.SubscriptionState", "SubscriptionState")
                        .WithMany("Orders")
                        .HasForeignKey("SubscriptionStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPayment");

                    b.Navigation("SubscriptionState");
                });

            modelBuilder.Entity("Pod.Data.Models.Mail.EMailAccountDataEMailContentTemplate", b =>
                {
                    b.HasOne("Pod.Data.Models.Mail.EMailAccountData", "EMailAccountData")
                        .WithMany("EmailContentTemplates")
                        .HasForeignKey("EMailAccountDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pod.Data.Models.Mail.EmailContentTemplate", "EmailContentTemplate")
                        .WithMany("EmailAccounts")
                        .HasForeignKey("EMailContentTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EMailAccountData");

                    b.Navigation("EmailContentTemplate");
                });

            modelBuilder.Entity("Pod.Data.Models.Mail.EMailReceiver", b =>
                {
                    b.HasOne("Pod.Data.Models.Mail.EmailSendOrder", "SendOrder")
                        .WithMany("Receivers")
                        .HasForeignKey("EmailSendOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SendOrder");
                });

            modelBuilder.Entity("Pod.Data.Models.Mail.EMailVariableValue", b =>
                {
                    b.HasOne("Pod.Data.Models.Mail.EmailSendOrder", "SendOrder")
                        .WithMany("Variables")
                        .HasForeignKey("EmailSendOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SendOrder");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.ApplicationRoot", b =>
                {
                    b.HasOne("Pod.Data.Models.Shell.DeviceIdentity", "DeviceIdentity")
                        .WithMany("ApplicationRoots")
                        .HasForeignKey("DeviceIdentityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Pod.Data.Models.Shell.Station", "Station")
                        .WithMany("ApplicationRoots")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceIdentity");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.ChangeRequest", b =>
                {
                    b.HasOne("Pod.Data.Models.Shell.Session", "Session")
                        .WithMany("ChangeRequests")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.ClosedConnection", b =>
                {
                    b.HasOne("Pod.Data.Models.Shell.DeviceIdentity", "DeviceIdentity")
                        .WithMany("ClosedConnections")
                        .HasForeignKey("DeviceIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pod.Data.Models.Servers.ShellServer", "Server")
                        .WithMany("ConnectionHistory")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pod.Data.Models.Shell.Station", "Station")
                        .WithMany("ConnectionHistory")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceIdentity");

                    b.Navigation("Server");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.ConnectionState", b =>
                {
                    b.HasOne("Pod.Data.Models.Shell.DeviceIdentity", "DeviceIdentity")
                        .WithOne("ConnectionState")
                        .HasForeignKey("Pod.Data.Models.Shell.ConnectionState", "DeviceIdentityId");

                    b.HasOne("Pod.Data.Models.Servers.ShellServer", "ShellServer")
                        .WithMany("ConnectedClients")
                        .HasForeignKey("ShellServerId");

                    b.HasOne("Pod.Data.Models.Shell.Station", "Station")
                        .WithOne("ConnectionState")
                        .HasForeignKey("Pod.Data.Models.Shell.ConnectionState", "StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceIdentity");

                    b.Navigation("ShellServer");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.LocalApp", b =>
                {
                    b.HasOne("Pod.Data.Models.Shell.ApplicationRoot", "ApplicationRoot")
                        .WithMany("LocalApps")
                        .HasForeignKey("ApplicationRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pod.Data.Models.Shell.UniqueApp", "UniqueApp")
                        .WithMany("LocalApps")
                        .HasForeignKey("UniqueAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationRoot");

                    b.Navigation("UniqueApp");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.Session", b =>
                {
                    b.HasOne("Pod.Data.Models.Shell.SessionRule", "SessionRule")
                        .WithOne("Session")
                        .HasForeignKey("Pod.Data.Models.Shell.Session", "SessionRuleId");

                    b.HasOne("Pod.Data.Models.Shell.Station", "Station")
                        .WithMany("Sessions")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionRule");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.SessionDetails", b =>
                {
                    b.HasOne("Pod.Data.Models.Shell.Session", "Session")
                        .WithOne("SessionDetails")
                        .HasForeignKey("Pod.Data.Models.Shell.SessionDetails", "SessionId");

                    b.HasOne("Pod.Data.Models.Shell.Station", "Station")
                        .WithOne("SessionDetails")
                        .HasForeignKey("Pod.Data.Models.Shell.SessionDetails", "StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.SessionRuleLocalApp", b =>
                {
                    b.HasOne("Pod.Data.Models.Shell.LocalApp", "LocalApp")
                        .WithMany("SessionRules")
                        .HasForeignKey("LocalAppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pod.Data.Models.Shell.SessionRule", "SessionRule")
                        .WithMany("AllowedApps")
                        .HasForeignKey("SessionRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalApp");

                    b.Navigation("SessionRule");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.Station", b =>
                {
                    b.HasOne("Pod.Data.Models.Users.ApplicationUser", "ApplicationUser")
                        .WithMany("Stations")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.StationApiKey", b =>
                {
                    b.HasOne("Pod.Data.Models.Shell.Station", "Station")
                        .WithMany("ApiKeys")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.StationSettings", b =>
                {
                    b.HasOne("Pod.Data.Models.Shell.Station", "Station")
                        .WithOne("StationSettings")
                        .HasForeignKey("Pod.Data.Models.Shell.StationSettings", "StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.SubscriptionState", b =>
                {
                    b.HasOne("Pod.Data.Models.Shell.Station", "Station")
                        .WithOne("SubscriptionState")
                        .HasForeignKey("Pod.Data.Models.Shell.SubscriptionState", "StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Pod.Data.Models.Mail.EmailVariable", b =>
                {
                    b.HasOne("Pod.Data.Models.Mail.EmailContentTemplate", null)
                        .WithMany("Variables")
                        .HasForeignKey("EmailContentTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pod.Data.Models.Billing.SubscriptionPayment", b =>
                {
                    b.Navigation("SubscriptionChange");

                    b.Navigation("SubscriptionOrder");
                });

            modelBuilder.Entity("Pod.Data.Models.Mail.EMailAccountData", b =>
                {
                    b.Navigation("EmailContentTemplates");
                });

            modelBuilder.Entity("Pod.Data.Models.Mail.EmailContentTemplate", b =>
                {
                    b.Navigation("EmailAccounts");

                    b.Navigation("Variables");
                });

            modelBuilder.Entity("Pod.Data.Models.Mail.EmailSendOrder", b =>
                {
                    b.Navigation("Receivers");

                    b.Navigation("Variables");
                });

            modelBuilder.Entity("Pod.Data.Models.Servers.ShellServer", b =>
                {
                    b.Navigation("ConnectedClients");

                    b.Navigation("ConnectionHistory");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.ApplicationRoot", b =>
                {
                    b.Navigation("LocalApps");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.DeviceIdentity", b =>
                {
                    b.Navigation("ApplicationRoots");

                    b.Navigation("ClosedConnections");

                    b.Navigation("ConnectionState");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.LocalApp", b =>
                {
                    b.Navigation("SessionRules");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.Session", b =>
                {
                    b.Navigation("ChangeRequests");

                    b.Navigation("SessionDetails");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.SessionRule", b =>
                {
                    b.Navigation("AllowedApps");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.Station", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("ApplicationRoots");

                    b.Navigation("ConnectionHistory");

                    b.Navigation("ConnectionState");

                    b.Navigation("SessionDetails");

                    b.Navigation("Sessions");

                    b.Navigation("StationSettings");

                    b.Navigation("SubscriptionState");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.SubscriptionState", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("SubscriptionChanges");
                });

            modelBuilder.Entity("Pod.Data.Models.Shell.UniqueApp", b =>
                {
                    b.Navigation("LocalApps");
                });

            modelBuilder.Entity("Pod.Data.Models.Users.ApplicationUser", b =>
                {
                    b.Navigation("Stations");
                });
#pragma warning restore 612, 618
        }
    }
}
