#region Licence
/****************************************************************
 *  Filename: MessagesConnectHost.cs
 *  ----------------------------------------------------------
 *  Author        Martin Meissner
 *  Date          2026-05-19
 *  Copyright (c) 2026 Martin Meissner.
 *                Released under the Apache License 2.0 as part of
 *                the open-source PlayOnDemand release.
 *
 *  SPDX-License-Identifier: Apache-2.0
 ****************************************************************/
#endregion
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MessagesConnectHost.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pod.Grpc.Messages.ConnectHost {

  /// <summary>Holder for reflection information generated from MessagesConnectHost.proto</summary>
  public static partial class MessagesConnectHostReflection {

    #region Descriptor
    /// <summary>File descriptor for MessagesConnectHost.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessagesConnectHostReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlNZXNzYWdlc0Nvbm5lY3RIb3N0LnByb3RvEh1Qb2QuR3JwYy5NZXNzYWdl",
            "cy5Db25uZWN0SG9zdBoUTWVzc2FnZXNTaGFyZWQucHJvdG8iiwEKElNoZWxs",
            "U2VydmVyUmVxdWVzdBISCgpJZGVudGl0eUlkGAEgASgJEhsKE01heEludGVy",
            "ZmFjZVZlcnNpb24YAiABKA0SRAoVUmVjb25uZWN0Q29ubmVjdGlvbklkGAMg",
            "ASgLMiUuUG9kLkdycGMuTWVzc2FnZXMuU2hhcmVkLkd1aWRBc0J5dGVzIpcB",
            "ChNTaGVsbFNlcnZlclJlc3BvbnNlEjsKDENvbm5lY3Rpb25JZBgBIAEoCzIl",
            "LlBvZC5HcnBjLk1lc3NhZ2VzLlNoYXJlZC5HdWlkQXNCeXRlcxITCgtIb3N0",
            "QWRkcmVzcxgCIAEoCRIMCgRQb3J0GAMgASgNEiAKGFJlcXVpcmVkSW50ZXJm",
            "YWNlVmVyc2lvbhgEIAEoDWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Pod.Grpc.Messages.Shared.MessagesSharedReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Pod.Grpc.Messages.ConnectHost.ShellServerRequest), global::Pod.Grpc.Messages.ConnectHost.ShellServerRequest.Parser, new[]{ "IdentityId", "MaxInterfaceVersion", "ReconnectConnectionId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pod.Grpc.Messages.ConnectHost.ShellServerResponse), global::Pod.Grpc.Messages.ConnectHost.ShellServerResponse.Parser, new[]{ "ConnectionId", "HostAddress", "Port", "RequiredInterfaceVersion" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ShellServerRequest : pb::IMessage<ShellServerRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ShellServerRequest> _parser = new pb::MessageParser<ShellServerRequest>(() => new ShellServerRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ShellServerRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pod.Grpc.Messages.ConnectHost.MessagesConnectHostReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ShellServerRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ShellServerRequest(ShellServerRequest other) : this() {
      identityId_ = other.identityId_;
      maxInterfaceVersion_ = other.maxInterfaceVersion_;
      reconnectConnectionId_ = other.reconnectConnectionId_ != null ? other.reconnectConnectionId_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ShellServerRequest Clone() {
      return new ShellServerRequest(this);
    }

    /// <summary>Field number for the "IdentityId" field.</summary>
    public const int IdentityIdFieldNumber = 1;
    private string identityId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdentityId {
      get { return identityId_; }
      set {
        identityId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "MaxInterfaceVersion" field.</summary>
    public const int MaxInterfaceVersionFieldNumber = 2;
    private uint maxInterfaceVersion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MaxInterfaceVersion {
      get { return maxInterfaceVersion_; }
      set {
        maxInterfaceVersion_ = value;
      }
    }

    /// <summary>Field number for the "ReconnectConnectionId" field.</summary>
    public const int ReconnectConnectionIdFieldNumber = 3;
    private global::Pod.Grpc.Messages.Shared.GuidAsBytes reconnectConnectionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pod.Grpc.Messages.Shared.GuidAsBytes ReconnectConnectionId {
      get { return reconnectConnectionId_; }
      set {
        reconnectConnectionId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ShellServerRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ShellServerRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdentityId != other.IdentityId) return false;
      if (MaxInterfaceVersion != other.MaxInterfaceVersion) return false;
      if (!object.Equals(ReconnectConnectionId, other.ReconnectConnectionId)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (IdentityId.Length != 0) hash ^= IdentityId.GetHashCode();
      if (MaxInterfaceVersion != 0) hash ^= MaxInterfaceVersion.GetHashCode();
      if (reconnectConnectionId_ != null) hash ^= ReconnectConnectionId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IdentityId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdentityId);
      }
      if (MaxInterfaceVersion != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(MaxInterfaceVersion);
      }
      if (reconnectConnectionId_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ReconnectConnectionId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IdentityId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdentityId);
      }
      if (MaxInterfaceVersion != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(MaxInterfaceVersion);
      }
      if (reconnectConnectionId_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ReconnectConnectionId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (IdentityId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdentityId);
      }
      if (MaxInterfaceVersion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MaxInterfaceVersion);
      }
      if (reconnectConnectionId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ReconnectConnectionId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ShellServerRequest other) {
      if (other == null) {
        return;
      }
      if (other.IdentityId.Length != 0) {
        IdentityId = other.IdentityId;
      }
      if (other.MaxInterfaceVersion != 0) {
        MaxInterfaceVersion = other.MaxInterfaceVersion;
      }
      if (other.reconnectConnectionId_ != null) {
        if (reconnectConnectionId_ == null) {
          ReconnectConnectionId = new global::Pod.Grpc.Messages.Shared.GuidAsBytes();
        }
        ReconnectConnectionId.MergeFrom(other.ReconnectConnectionId);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            IdentityId = input.ReadString();
            break;
          }
          case 16: {
            MaxInterfaceVersion = input.ReadUInt32();
            break;
          }
          case 26: {
            if (reconnectConnectionId_ == null) {
              ReconnectConnectionId = new global::Pod.Grpc.Messages.Shared.GuidAsBytes();
            }
            input.ReadMessage(ReconnectConnectionId);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            IdentityId = input.ReadString();
            break;
          }
          case 16: {
            MaxInterfaceVersion = input.ReadUInt32();
            break;
          }
          case 26: {
            if (reconnectConnectionId_ == null) {
              ReconnectConnectionId = new global::Pod.Grpc.Messages.Shared.GuidAsBytes();
            }
            input.ReadMessage(ReconnectConnectionId);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ShellServerResponse : pb::IMessage<ShellServerResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ShellServerResponse> _parser = new pb::MessageParser<ShellServerResponse>(() => new ShellServerResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ShellServerResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pod.Grpc.Messages.ConnectHost.MessagesConnectHostReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ShellServerResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ShellServerResponse(ShellServerResponse other) : this() {
      connectionId_ = other.connectionId_ != null ? other.connectionId_.Clone() : null;
      hostAddress_ = other.hostAddress_;
      port_ = other.port_;
      requiredInterfaceVersion_ = other.requiredInterfaceVersion_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ShellServerResponse Clone() {
      return new ShellServerResponse(this);
    }

    /// <summary>Field number for the "ConnectionId" field.</summary>
    public const int ConnectionIdFieldNumber = 1;
    private global::Pod.Grpc.Messages.Shared.GuidAsBytes connectionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pod.Grpc.Messages.Shared.GuidAsBytes ConnectionId {
      get { return connectionId_; }
      set {
        connectionId_ = value;
      }
    }

    /// <summary>Field number for the "HostAddress" field.</summary>
    public const int HostAddressFieldNumber = 2;
    private string hostAddress_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string HostAddress {
      get { return hostAddress_; }
      set {
        hostAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Port" field.</summary>
    public const int PortFieldNumber = 3;
    private uint port_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Port {
      get { return port_; }
      set {
        port_ = value;
      }
    }

    /// <summary>Field number for the "RequiredInterfaceVersion" field.</summary>
    public const int RequiredInterfaceVersionFieldNumber = 4;
    private uint requiredInterfaceVersion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RequiredInterfaceVersion {
      get { return requiredInterfaceVersion_; }
      set {
        requiredInterfaceVersion_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ShellServerResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ShellServerResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ConnectionId, other.ConnectionId)) return false;
      if (HostAddress != other.HostAddress) return false;
      if (Port != other.Port) return false;
      if (RequiredInterfaceVersion != other.RequiredInterfaceVersion) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (connectionId_ != null) hash ^= ConnectionId.GetHashCode();
      if (HostAddress.Length != 0) hash ^= HostAddress.GetHashCode();
      if (Port != 0) hash ^= Port.GetHashCode();
      if (RequiredInterfaceVersion != 0) hash ^= RequiredInterfaceVersion.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (connectionId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ConnectionId);
      }
      if (HostAddress.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(HostAddress);
      }
      if (Port != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Port);
      }
      if (RequiredInterfaceVersion != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(RequiredInterfaceVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (connectionId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ConnectionId);
      }
      if (HostAddress.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(HostAddress);
      }
      if (Port != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Port);
      }
      if (RequiredInterfaceVersion != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(RequiredInterfaceVersion);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (connectionId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ConnectionId);
      }
      if (HostAddress.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(HostAddress);
      }
      if (Port != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Port);
      }
      if (RequiredInterfaceVersion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RequiredInterfaceVersion);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ShellServerResponse other) {
      if (other == null) {
        return;
      }
      if (other.connectionId_ != null) {
        if (connectionId_ == null) {
          ConnectionId = new global::Pod.Grpc.Messages.Shared.GuidAsBytes();
        }
        ConnectionId.MergeFrom(other.ConnectionId);
      }
      if (other.HostAddress.Length != 0) {
        HostAddress = other.HostAddress;
      }
      if (other.Port != 0) {
        Port = other.Port;
      }
      if (other.RequiredInterfaceVersion != 0) {
        RequiredInterfaceVersion = other.RequiredInterfaceVersion;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (connectionId_ == null) {
              ConnectionId = new global::Pod.Grpc.Messages.Shared.GuidAsBytes();
            }
            input.ReadMessage(ConnectionId);
            break;
          }
          case 18: {
            HostAddress = input.ReadString();
            break;
          }
          case 24: {
            Port = input.ReadUInt32();
            break;
          }
          case 32: {
            RequiredInterfaceVersion = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (connectionId_ == null) {
              ConnectionId = new global::Pod.Grpc.Messages.Shared.GuidAsBytes();
            }
            input.ReadMessage(ConnectionId);
            break;
          }
          case 18: {
            HostAddress = input.ReadString();
            break;
          }
          case 24: {
            Port = input.ReadUInt32();
            break;
          }
          case 32: {
            RequiredInterfaceVersion = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
