#region Licence
/****************************************************************
 *  Filename: ServiceShellHostGrpc.cs
 *  ----------------------------------------------------------
 *  Author        Martin Meissner
 *  Date          2026-05-19
 *  Copyright (c) 2026 Martin Meissner.
 *                Released under the Apache License 2.0 as part of
 *                the open-source PlayOnDemand release.
 *
 *  SPDX-License-Identifier: Apache-2.0
 ****************************************************************/
#endregion
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ServiceShellHost.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Pod.Grpc.ShellHost {
  public static partial class ShellHostServiceGrpc
  {
    static readonly string __ServiceName = "Pod.Grpc.ShellHost.ShellHostServiceGrpc";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellHost.ConnectRequest> __Marshaller_Pod_Grpc_Messages_ShellHost_ConnectRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellHost.ConnectRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellHost.ConnectResponse> __Marshaller_Pod_Grpc_Messages_ShellHost_ConnectResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellHost.ConnectResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellHost.NotificationRequest> __Marshaller_Pod_Grpc_Messages_ShellHost_NotificationRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellHost.NotificationRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellHost.ClientNotification> __Marshaller_Pod_Grpc_Messages_ShellHost_ClientNotification = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellHost.ClientNotification.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellHost.ServerSettingsRequest> __Marshaller_Pod_Grpc_Messages_ShellHost_ServerSettingsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellHost.ServerSettingsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellHost.ServerSettingsResponse> __Marshaller_Pod_Grpc_Messages_ShellHost_ServerSettingsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellHost.ServerSettingsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellHost.ClientSettingsRequest> __Marshaller_Pod_Grpc_Messages_ShellHost_ClientSettingsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellHost.ClientSettingsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellHost.ClientSettingsResponse> __Marshaller_Pod_Grpc_Messages_ShellHost_ClientSettingsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellHost.ClientSettingsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellHost.HeartbeatRequest> __Marshaller_Pod_Grpc_Messages_ShellHost_HeartbeatRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellHost.HeartbeatRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellHost.HeartbeatResponse> __Marshaller_Pod_Grpc_Messages_ShellHost_HeartbeatResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellHost.HeartbeatResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellHost.LoginRequest> __Marshaller_Pod_Grpc_Messages_ShellHost_LoginRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellHost.LoginRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellHost.LoginRequestResponse> __Marshaller_Pod_Grpc_Messages_ShellHost_LoginRequestResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellHost.LoginRequestResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellHost.RequestedLoginRequest> __Marshaller_Pod_Grpc_Messages_ShellHost_RequestedLoginRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellHost.RequestedLoginRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellHost.RequestedLoginResponse> __Marshaller_Pod_Grpc_Messages_ShellHost_RequestedLoginResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellHost.RequestedLoginResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellHost.LoginIntentionReplyRequest> __Marshaller_Pod_Grpc_Messages_ShellHost_LoginIntentionReplyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellHost.LoginIntentionReplyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellHost.LoginIntentionReplyResponse> __Marshaller_Pod_Grpc_Messages_ShellHost_LoginIntentionReplyResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellHost.LoginIntentionReplyResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellHost.SessionStateRequest> __Marshaller_Pod_Grpc_Messages_ShellHost_SessionStateRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellHost.SessionStateRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellHost.SessionStateResponse> __Marshaller_Pod_Grpc_Messages_ShellHost_SessionStateResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellHost.SessionStateResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellHost.LogoutRequest> __Marshaller_Pod_Grpc_Messages_ShellHost_LogoutRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellHost.LogoutRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellHost.LogoutResponse> __Marshaller_Pod_Grpc_Messages_ShellHost_LogoutResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellHost.LogoutResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellHost.DisconnectRequest> __Marshaller_Pod_Grpc_Messages_ShellHost_DisconnectRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellHost.DisconnectRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellHost.DisconnectResponse> __Marshaller_Pod_Grpc_Messages_ShellHost_DisconnectResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellHost.DisconnectResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Pod.Grpc.Messages.ShellHost.ConnectRequest, global::Pod.Grpc.Messages.ShellHost.ConnectResponse> __Method_Connect = new grpc::Method<global::Pod.Grpc.Messages.ShellHost.ConnectRequest, global::Pod.Grpc.Messages.ShellHost.ConnectResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Connect",
        __Marshaller_Pod_Grpc_Messages_ShellHost_ConnectRequest,
        __Marshaller_Pod_Grpc_Messages_ShellHost_ConnectResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Pod.Grpc.Messages.ShellHost.NotificationRequest, global::Pod.Grpc.Messages.ShellHost.ClientNotification> __Method_GetNotifications = new grpc::Method<global::Pod.Grpc.Messages.ShellHost.NotificationRequest, global::Pod.Grpc.Messages.ShellHost.ClientNotification>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetNotifications",
        __Marshaller_Pod_Grpc_Messages_ShellHost_NotificationRequest,
        __Marshaller_Pod_Grpc_Messages_ShellHost_ClientNotification);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Pod.Grpc.Messages.ShellHost.ServerSettingsRequest, global::Pod.Grpc.Messages.ShellHost.ServerSettingsResponse> __Method_GetServerSettings = new grpc::Method<global::Pod.Grpc.Messages.ShellHost.ServerSettingsRequest, global::Pod.Grpc.Messages.ShellHost.ServerSettingsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetServerSettings",
        __Marshaller_Pod_Grpc_Messages_ShellHost_ServerSettingsRequest,
        __Marshaller_Pod_Grpc_Messages_ShellHost_ServerSettingsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Pod.Grpc.Messages.ShellHost.ClientSettingsRequest, global::Pod.Grpc.Messages.ShellHost.ClientSettingsResponse> __Method_GetClientSettings = new grpc::Method<global::Pod.Grpc.Messages.ShellHost.ClientSettingsRequest, global::Pod.Grpc.Messages.ShellHost.ClientSettingsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetClientSettings",
        __Marshaller_Pod_Grpc_Messages_ShellHost_ClientSettingsRequest,
        __Marshaller_Pod_Grpc_Messages_ShellHost_ClientSettingsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Pod.Grpc.Messages.ShellHost.HeartbeatRequest, global::Pod.Grpc.Messages.ShellHost.HeartbeatResponse> __Method_SendHeartbeat = new grpc::Method<global::Pod.Grpc.Messages.ShellHost.HeartbeatRequest, global::Pod.Grpc.Messages.ShellHost.HeartbeatResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendHeartbeat",
        __Marshaller_Pod_Grpc_Messages_ShellHost_HeartbeatRequest,
        __Marshaller_Pod_Grpc_Messages_ShellHost_HeartbeatResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Pod.Grpc.Messages.ShellHost.LoginRequest, global::Pod.Grpc.Messages.ShellHost.LoginRequestResponse> __Method_SendLoginIntention = new grpc::Method<global::Pod.Grpc.Messages.ShellHost.LoginRequest, global::Pod.Grpc.Messages.ShellHost.LoginRequestResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendLoginIntention",
        __Marshaller_Pod_Grpc_Messages_ShellHost_LoginRequest,
        __Marshaller_Pod_Grpc_Messages_ShellHost_LoginRequestResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Pod.Grpc.Messages.ShellHost.RequestedLoginRequest, global::Pod.Grpc.Messages.ShellHost.RequestedLoginResponse> __Method_GetLoginIntention = new grpc::Method<global::Pod.Grpc.Messages.ShellHost.RequestedLoginRequest, global::Pod.Grpc.Messages.ShellHost.RequestedLoginResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetLoginIntention",
        __Marshaller_Pod_Grpc_Messages_ShellHost_RequestedLoginRequest,
        __Marshaller_Pod_Grpc_Messages_ShellHost_RequestedLoginResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Pod.Grpc.Messages.ShellHost.LoginIntentionReplyRequest, global::Pod.Grpc.Messages.ShellHost.LoginIntentionReplyResponse> __Method_SendLoginResponse = new grpc::Method<global::Pod.Grpc.Messages.ShellHost.LoginIntentionReplyRequest, global::Pod.Grpc.Messages.ShellHost.LoginIntentionReplyResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendLoginResponse",
        __Marshaller_Pod_Grpc_Messages_ShellHost_LoginIntentionReplyRequest,
        __Marshaller_Pod_Grpc_Messages_ShellHost_LoginIntentionReplyResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Pod.Grpc.Messages.ShellHost.SessionStateRequest, global::Pod.Grpc.Messages.ShellHost.SessionStateResponse> __Method_GetSessionState = new grpc::Method<global::Pod.Grpc.Messages.ShellHost.SessionStateRequest, global::Pod.Grpc.Messages.ShellHost.SessionStateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetSessionState",
        __Marshaller_Pod_Grpc_Messages_ShellHost_SessionStateRequest,
        __Marshaller_Pod_Grpc_Messages_ShellHost_SessionStateResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Pod.Grpc.Messages.ShellHost.LogoutRequest, global::Pod.Grpc.Messages.ShellHost.LogoutResponse> __Method_SendLogoutRequest = new grpc::Method<global::Pod.Grpc.Messages.ShellHost.LogoutRequest, global::Pod.Grpc.Messages.ShellHost.LogoutResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendLogoutRequest",
        __Marshaller_Pod_Grpc_Messages_ShellHost_LogoutRequest,
        __Marshaller_Pod_Grpc_Messages_ShellHost_LogoutResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Pod.Grpc.Messages.ShellHost.DisconnectRequest, global::Pod.Grpc.Messages.ShellHost.DisconnectResponse> __Method_Disconnect = new grpc::Method<global::Pod.Grpc.Messages.ShellHost.DisconnectRequest, global::Pod.Grpc.Messages.ShellHost.DisconnectResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Disconnect",
        __Marshaller_Pod_Grpc_Messages_ShellHost_DisconnectRequest,
        __Marshaller_Pod_Grpc_Messages_ShellHost_DisconnectResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Pod.Grpc.ShellHost.ServiceShellHostReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ShellHostServiceGrpc</summary>
    [grpc::BindServiceMethod(typeof(ShellHostServiceGrpc), "BindService")]
    public abstract partial class ShellHostServiceGrpcBase
    {
      /// <summary>
      ///Request to Server from a Client to Connect  
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Pod.Grpc.Messages.ShellHost.ConnectResponse> Connect(global::Pod.Grpc.Messages.ShellHost.ConnectRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///Get Server to Client stream providing Server Notifications/Messages
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task GetNotifications(global::Pod.Grpc.Messages.ShellHost.NotificationRequest request, grpc::IServerStreamWriter<global::Pod.Grpc.Messages.ShellHost.ClientNotification> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///Receive Server Settings/Rules that need to be followed by Client
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Pod.Grpc.Messages.ShellHost.ServerSettingsResponse> GetServerSettings(global::Pod.Grpc.Messages.ShellHost.ServerSettingsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///Receive Client Settings as Names, Modes and so on
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Pod.Grpc.Messages.ShellHost.ClientSettingsResponse> GetClientSettings(global::Pod.Grpc.Messages.ShellHost.ClientSettingsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///Sends an Heartbeat to the Server as keep alive signal on Server Side
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Pod.Grpc.Messages.ShellHost.HeartbeatResponse> SendHeartbeat(global::Pod.Grpc.Messages.ShellHost.HeartbeatRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///Create request for a new Login Intention
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Pod.Grpc.Messages.ShellHost.LoginRequestResponse> SendLoginIntention(global::Pod.Grpc.Messages.ShellHost.LoginRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///Receive a pending Login Intention 
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Pod.Grpc.Messages.ShellHost.RequestedLoginResponse> GetLoginIntention(global::Pod.Grpc.Messages.ShellHost.RequestedLoginRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///Send a response for a Login Intention 
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Pod.Grpc.Messages.ShellHost.LoginIntentionReplyResponse> SendLoginResponse(global::Pod.Grpc.Messages.ShellHost.LoginIntentionReplyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///Receive current Session State if one is availible
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Pod.Grpc.Messages.ShellHost.SessionStateResponse> GetSessionState(global::Pod.Grpc.Messages.ShellHost.SessionStateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///Send Logout from an current Session
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Pod.Grpc.Messages.ShellHost.LogoutResponse> SendLogoutRequest(global::Pod.Grpc.Messages.ShellHost.LogoutRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///Inform Server about Client is Disconnecting
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Pod.Grpc.Messages.ShellHost.DisconnectResponse> Disconnect(global::Pod.Grpc.Messages.ShellHost.DisconnectRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ShellHostServiceGrpc</summary>
    public partial class ShellHostServiceGrpcClient : grpc::ClientBase<ShellHostServiceGrpcClient>
    {
      /// <summary>Creates a new client for ShellHostServiceGrpc</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ShellHostServiceGrpcClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ShellHostServiceGrpc that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ShellHostServiceGrpcClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ShellHostServiceGrpcClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ShellHostServiceGrpcClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///Request to Server from a Client to Connect  
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellHost.ConnectResponse Connect(global::Pod.Grpc.Messages.ShellHost.ConnectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Connect(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Request to Server from a Client to Connect  
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellHost.ConnectResponse Connect(global::Pod.Grpc.Messages.ShellHost.ConnectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Connect, null, options, request);
      }
      /// <summary>
      ///Request to Server from a Client to Connect  
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellHost.ConnectResponse> ConnectAsync(global::Pod.Grpc.Messages.ShellHost.ConnectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ConnectAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Request to Server from a Client to Connect  
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellHost.ConnectResponse> ConnectAsync(global::Pod.Grpc.Messages.ShellHost.ConnectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Connect, null, options, request);
      }
      /// <summary>
      ///Get Server to Client stream providing Server Notifications/Messages
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Pod.Grpc.Messages.ShellHost.ClientNotification> GetNotifications(global::Pod.Grpc.Messages.ShellHost.NotificationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetNotifications(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Get Server to Client stream providing Server Notifications/Messages
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Pod.Grpc.Messages.ShellHost.ClientNotification> GetNotifications(global::Pod.Grpc.Messages.ShellHost.NotificationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetNotifications, null, options, request);
      }
      /// <summary>
      ///Receive Server Settings/Rules that need to be followed by Client
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellHost.ServerSettingsResponse GetServerSettings(global::Pod.Grpc.Messages.ShellHost.ServerSettingsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetServerSettings(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Receive Server Settings/Rules that need to be followed by Client
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellHost.ServerSettingsResponse GetServerSettings(global::Pod.Grpc.Messages.ShellHost.ServerSettingsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetServerSettings, null, options, request);
      }
      /// <summary>
      ///Receive Server Settings/Rules that need to be followed by Client
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellHost.ServerSettingsResponse> GetServerSettingsAsync(global::Pod.Grpc.Messages.ShellHost.ServerSettingsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetServerSettingsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Receive Server Settings/Rules that need to be followed by Client
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellHost.ServerSettingsResponse> GetServerSettingsAsync(global::Pod.Grpc.Messages.ShellHost.ServerSettingsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetServerSettings, null, options, request);
      }
      /// <summary>
      ///Receive Client Settings as Names, Modes and so on
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellHost.ClientSettingsResponse GetClientSettings(global::Pod.Grpc.Messages.ShellHost.ClientSettingsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetClientSettings(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Receive Client Settings as Names, Modes and so on
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellHost.ClientSettingsResponse GetClientSettings(global::Pod.Grpc.Messages.ShellHost.ClientSettingsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetClientSettings, null, options, request);
      }
      /// <summary>
      ///Receive Client Settings as Names, Modes and so on
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellHost.ClientSettingsResponse> GetClientSettingsAsync(global::Pod.Grpc.Messages.ShellHost.ClientSettingsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetClientSettingsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Receive Client Settings as Names, Modes and so on
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellHost.ClientSettingsResponse> GetClientSettingsAsync(global::Pod.Grpc.Messages.ShellHost.ClientSettingsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetClientSettings, null, options, request);
      }
      /// <summary>
      ///Sends an Heartbeat to the Server as keep alive signal on Server Side
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellHost.HeartbeatResponse SendHeartbeat(global::Pod.Grpc.Messages.ShellHost.HeartbeatRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendHeartbeat(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Sends an Heartbeat to the Server as keep alive signal on Server Side
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellHost.HeartbeatResponse SendHeartbeat(global::Pod.Grpc.Messages.ShellHost.HeartbeatRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendHeartbeat, null, options, request);
      }
      /// <summary>
      ///Sends an Heartbeat to the Server as keep alive signal on Server Side
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellHost.HeartbeatResponse> SendHeartbeatAsync(global::Pod.Grpc.Messages.ShellHost.HeartbeatRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendHeartbeatAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Sends an Heartbeat to the Server as keep alive signal on Server Side
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellHost.HeartbeatResponse> SendHeartbeatAsync(global::Pod.Grpc.Messages.ShellHost.HeartbeatRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendHeartbeat, null, options, request);
      }
      /// <summary>
      ///Create request for a new Login Intention
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellHost.LoginRequestResponse SendLoginIntention(global::Pod.Grpc.Messages.ShellHost.LoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendLoginIntention(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Create request for a new Login Intention
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellHost.LoginRequestResponse SendLoginIntention(global::Pod.Grpc.Messages.ShellHost.LoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendLoginIntention, null, options, request);
      }
      /// <summary>
      ///Create request for a new Login Intention
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellHost.LoginRequestResponse> SendLoginIntentionAsync(global::Pod.Grpc.Messages.ShellHost.LoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendLoginIntentionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Create request for a new Login Intention
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellHost.LoginRequestResponse> SendLoginIntentionAsync(global::Pod.Grpc.Messages.ShellHost.LoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendLoginIntention, null, options, request);
      }
      /// <summary>
      ///Receive a pending Login Intention 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellHost.RequestedLoginResponse GetLoginIntention(global::Pod.Grpc.Messages.ShellHost.RequestedLoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetLoginIntention(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Receive a pending Login Intention 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellHost.RequestedLoginResponse GetLoginIntention(global::Pod.Grpc.Messages.ShellHost.RequestedLoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetLoginIntention, null, options, request);
      }
      /// <summary>
      ///Receive a pending Login Intention 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellHost.RequestedLoginResponse> GetLoginIntentionAsync(global::Pod.Grpc.Messages.ShellHost.RequestedLoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetLoginIntentionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Receive a pending Login Intention 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellHost.RequestedLoginResponse> GetLoginIntentionAsync(global::Pod.Grpc.Messages.ShellHost.RequestedLoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetLoginIntention, null, options, request);
      }
      /// <summary>
      ///Send a response for a Login Intention 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellHost.LoginIntentionReplyResponse SendLoginResponse(global::Pod.Grpc.Messages.ShellHost.LoginIntentionReplyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendLoginResponse(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Send a response for a Login Intention 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellHost.LoginIntentionReplyResponse SendLoginResponse(global::Pod.Grpc.Messages.ShellHost.LoginIntentionReplyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendLoginResponse, null, options, request);
      }
      /// <summary>
      ///Send a response for a Login Intention 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellHost.LoginIntentionReplyResponse> SendLoginResponseAsync(global::Pod.Grpc.Messages.ShellHost.LoginIntentionReplyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendLoginResponseAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Send a response for a Login Intention 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellHost.LoginIntentionReplyResponse> SendLoginResponseAsync(global::Pod.Grpc.Messages.ShellHost.LoginIntentionReplyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendLoginResponse, null, options, request);
      }
      /// <summary>
      ///Receive current Session State if one is availible
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellHost.SessionStateResponse GetSessionState(global::Pod.Grpc.Messages.ShellHost.SessionStateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSessionState(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Receive current Session State if one is availible
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellHost.SessionStateResponse GetSessionState(global::Pod.Grpc.Messages.ShellHost.SessionStateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetSessionState, null, options, request);
      }
      /// <summary>
      ///Receive current Session State if one is availible
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellHost.SessionStateResponse> GetSessionStateAsync(global::Pod.Grpc.Messages.ShellHost.SessionStateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSessionStateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Receive current Session State if one is availible
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellHost.SessionStateResponse> GetSessionStateAsync(global::Pod.Grpc.Messages.ShellHost.SessionStateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetSessionState, null, options, request);
      }
      /// <summary>
      ///Send Logout from an current Session
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellHost.LogoutResponse SendLogoutRequest(global::Pod.Grpc.Messages.ShellHost.LogoutRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendLogoutRequest(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Send Logout from an current Session
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellHost.LogoutResponse SendLogoutRequest(global::Pod.Grpc.Messages.ShellHost.LogoutRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendLogoutRequest, null, options, request);
      }
      /// <summary>
      ///Send Logout from an current Session
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellHost.LogoutResponse> SendLogoutRequestAsync(global::Pod.Grpc.Messages.ShellHost.LogoutRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendLogoutRequestAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Send Logout from an current Session
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellHost.LogoutResponse> SendLogoutRequestAsync(global::Pod.Grpc.Messages.ShellHost.LogoutRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendLogoutRequest, null, options, request);
      }
      /// <summary>
      ///Inform Server about Client is Disconnecting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellHost.DisconnectResponse Disconnect(global::Pod.Grpc.Messages.ShellHost.DisconnectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Disconnect(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Inform Server about Client is Disconnecting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellHost.DisconnectResponse Disconnect(global::Pod.Grpc.Messages.ShellHost.DisconnectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Disconnect, null, options, request);
      }
      /// <summary>
      ///Inform Server about Client is Disconnecting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellHost.DisconnectResponse> DisconnectAsync(global::Pod.Grpc.Messages.ShellHost.DisconnectRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DisconnectAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Inform Server about Client is Disconnecting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellHost.DisconnectResponse> DisconnectAsync(global::Pod.Grpc.Messages.ShellHost.DisconnectRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Disconnect, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ShellHostServiceGrpcClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ShellHostServiceGrpcClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(ShellHostServiceGrpcBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Connect, serviceImpl.Connect)
          .AddMethod(__Method_GetNotifications, serviceImpl.GetNotifications)
          .AddMethod(__Method_GetServerSettings, serviceImpl.GetServerSettings)
          .AddMethod(__Method_GetClientSettings, serviceImpl.GetClientSettings)
          .AddMethod(__Method_SendHeartbeat, serviceImpl.SendHeartbeat)
          .AddMethod(__Method_SendLoginIntention, serviceImpl.SendLoginIntention)
          .AddMethod(__Method_GetLoginIntention, serviceImpl.GetLoginIntention)
          .AddMethod(__Method_SendLoginResponse, serviceImpl.SendLoginResponse)
          .AddMethod(__Method_GetSessionState, serviceImpl.GetSessionState)
          .AddMethod(__Method_SendLogoutRequest, serviceImpl.SendLogoutRequest)
          .AddMethod(__Method_Disconnect, serviceImpl.Disconnect).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ShellHostServiceGrpcBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Connect, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Pod.Grpc.Messages.ShellHost.ConnectRequest, global::Pod.Grpc.Messages.ShellHost.ConnectResponse>(serviceImpl.Connect));
      serviceBinder.AddMethod(__Method_GetNotifications, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Pod.Grpc.Messages.ShellHost.NotificationRequest, global::Pod.Grpc.Messages.ShellHost.ClientNotification>(serviceImpl.GetNotifications));
      serviceBinder.AddMethod(__Method_GetServerSettings, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Pod.Grpc.Messages.ShellHost.ServerSettingsRequest, global::Pod.Grpc.Messages.ShellHost.ServerSettingsResponse>(serviceImpl.GetServerSettings));
      serviceBinder.AddMethod(__Method_GetClientSettings, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Pod.Grpc.Messages.ShellHost.ClientSettingsRequest, global::Pod.Grpc.Messages.ShellHost.ClientSettingsResponse>(serviceImpl.GetClientSettings));
      serviceBinder.AddMethod(__Method_SendHeartbeat, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Pod.Grpc.Messages.ShellHost.HeartbeatRequest, global::Pod.Grpc.Messages.ShellHost.HeartbeatResponse>(serviceImpl.SendHeartbeat));
      serviceBinder.AddMethod(__Method_SendLoginIntention, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Pod.Grpc.Messages.ShellHost.LoginRequest, global::Pod.Grpc.Messages.ShellHost.LoginRequestResponse>(serviceImpl.SendLoginIntention));
      serviceBinder.AddMethod(__Method_GetLoginIntention, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Pod.Grpc.Messages.ShellHost.RequestedLoginRequest, global::Pod.Grpc.Messages.ShellHost.RequestedLoginResponse>(serviceImpl.GetLoginIntention));
      serviceBinder.AddMethod(__Method_SendLoginResponse, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Pod.Grpc.Messages.ShellHost.LoginIntentionReplyRequest, global::Pod.Grpc.Messages.ShellHost.LoginIntentionReplyResponse>(serviceImpl.SendLoginResponse));
      serviceBinder.AddMethod(__Method_GetSessionState, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Pod.Grpc.Messages.ShellHost.SessionStateRequest, global::Pod.Grpc.Messages.ShellHost.SessionStateResponse>(serviceImpl.GetSessionState));
      serviceBinder.AddMethod(__Method_SendLogoutRequest, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Pod.Grpc.Messages.ShellHost.LogoutRequest, global::Pod.Grpc.Messages.ShellHost.LogoutResponse>(serviceImpl.SendLogoutRequest));
      serviceBinder.AddMethod(__Method_Disconnect, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Pod.Grpc.Messages.ShellHost.DisconnectRequest, global::Pod.Grpc.Messages.ShellHost.DisconnectResponse>(serviceImpl.Disconnect));
    }

  }
}
#endregion
