#region Licence
/****************************************************************
 *  Filename: ServiceConnectHost.cs
 *  ----------------------------------------------------------
 *  Author        Martin Meissner
 *  Date          2026-05-19
 *  Copyright (c) 2026 Martin Meissner.
 *                Released under the Apache License 2.0 as part of
 *                the open-source PlayOnDemand release.
 *
 *  SPDX-License-Identifier: Apache-2.0
 ****************************************************************/
#endregion
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ServiceConnectHost.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pod.Grpc.ConnectHost {

  /// <summary>Holder for reflection information generated from ServiceConnectHost.proto</summary>
  public static partial class ServiceConnectHostReflection {

    #region Descriptor
    /// <summary>File descriptor for ServiceConnectHost.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceConnectHostReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhTZXJ2aWNlQ29ubmVjdEhvc3QucHJvdG8SFFBvZC5HcnBjLkNvbm5lY3RI",
            "b3N0GhlNZXNzYWdlc0Nvbm5lY3RIb3N0LnByb3RvMowBChZDb25uZWN0SG9z",
            "dFNlcnZpY2VHcnBjEnIKB0dldEhvc3QSMS5Qb2QuR3JwYy5NZXNzYWdlcy5D",
            "b25uZWN0SG9zdC5TaGVsbFNlcnZlclJlcXVlc3QaMi5Qb2QuR3JwYy5NZXNz",
            "YWdlcy5Db25uZWN0SG9zdC5TaGVsbFNlcnZlclJlc3BvbnNlIgBiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Pod.Grpc.Messages.ConnectHost.MessagesConnectHostReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
