#region Licence
/****************************************************************
 *  Filename: ServiceShellHost.cs
 *  ----------------------------------------------------------
 *  Author        Martin Meissner
 *  Date          2026-05-19
 *  Copyright (c) 2026 Martin Meissner.
 *                Released under the Apache License 2.0 as part of
 *                the open-source PlayOnDemand release.
 *
 *  SPDX-License-Identifier: Apache-2.0
 ****************************************************************/
#endregion
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ServiceShellHost.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pod.Grpc.ShellHost {

  /// <summary>Holder for reflection information generated from ServiceShellHost.proto</summary>
  public static partial class ServiceShellHostReflection {

    #region Descriptor
    /// <summary>File descriptor for ServiceShellHost.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceShellHostReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZTZXJ2aWNlU2hlbGxIb3N0LnByb3RvEhJQb2QuR3JwYy5TaGVsbEhvc3Qa",
            "F01lc3NhZ2VzU2hlbGxIb3N0LnByb3RvMscKChRTaGVsbEhvc3RTZXJ2aWNl",
            "R3JwYxJmCgdDb25uZWN0EisuUG9kLkdycGMuTWVzc2FnZXMuU2hlbGxIb3N0",
            "LkNvbm5lY3RSZXF1ZXN0GiwuUG9kLkdycGMuTWVzc2FnZXMuU2hlbGxIb3N0",
            "LkNvbm5lY3RSZXNwb25zZSIAEnkKEEdldE5vdGlmaWNhdGlvbnMSMC5Qb2Qu",
            "R3JwYy5NZXNzYWdlcy5TaGVsbEhvc3QuTm90aWZpY2F0aW9uUmVxdWVzdBov",
            "LlBvZC5HcnBjLk1lc3NhZ2VzLlNoZWxsSG9zdC5DbGllbnROb3RpZmljYXRp",
            "b24iADABEn4KEUdldFNlcnZlclNldHRpbmdzEjIuUG9kLkdycGMuTWVzc2Fn",
            "ZXMuU2hlbGxIb3N0LlNlcnZlclNldHRpbmdzUmVxdWVzdBozLlBvZC5HcnBj",
            "Lk1lc3NhZ2VzLlNoZWxsSG9zdC5TZXJ2ZXJTZXR0aW5nc1Jlc3BvbnNlIgAS",
            "fgoRR2V0Q2xpZW50U2V0dGluZ3MSMi5Qb2QuR3JwYy5NZXNzYWdlcy5TaGVs",
            "bEhvc3QuQ2xpZW50U2V0dGluZ3NSZXF1ZXN0GjMuUG9kLkdycGMuTWVzc2Fn",
            "ZXMuU2hlbGxIb3N0LkNsaWVudFNldHRpbmdzUmVzcG9uc2UiABJwCg1TZW5k",
            "SGVhcnRiZWF0Ei0uUG9kLkdycGMuTWVzc2FnZXMuU2hlbGxIb3N0LkhlYXJ0",
            "YmVhdFJlcXVlc3QaLi5Qb2QuR3JwYy5NZXNzYWdlcy5TaGVsbEhvc3QuSGVh",
            "cnRiZWF0UmVzcG9uc2UiABJ0ChJTZW5kTG9naW5JbnRlbnRpb24SKS5Qb2Qu",
            "R3JwYy5NZXNzYWdlcy5TaGVsbEhvc3QuTG9naW5SZXF1ZXN0GjEuUG9kLkdy",
            "cGMuTWVzc2FnZXMuU2hlbGxIb3N0LkxvZ2luUmVxdWVzdFJlc3BvbnNlIgAS",
            "fgoRR2V0TG9naW5JbnRlbnRpb24SMi5Qb2QuR3JwYy5NZXNzYWdlcy5TaGVs",
            "bEhvc3QuUmVxdWVzdGVkTG9naW5SZXF1ZXN0GjMuUG9kLkdycGMuTWVzc2Fn",
            "ZXMuU2hlbGxIb3N0LlJlcXVlc3RlZExvZ2luUmVzcG9uc2UiABKIAQoRU2Vu",
            "ZExvZ2luUmVzcG9uc2USNy5Qb2QuR3JwYy5NZXNzYWdlcy5TaGVsbEhvc3Qu",
            "TG9naW5JbnRlbnRpb25SZXBseVJlcXVlc3QaOC5Qb2QuR3JwYy5NZXNzYWdl",
            "cy5TaGVsbEhvc3QuTG9naW5JbnRlbnRpb25SZXBseVJlc3BvbnNlIgASeAoP",
            "R2V0U2Vzc2lvblN0YXRlEjAuUG9kLkdycGMuTWVzc2FnZXMuU2hlbGxIb3N0",
            "LlNlc3Npb25TdGF0ZVJlcXVlc3QaMS5Qb2QuR3JwYy5NZXNzYWdlcy5TaGVs",
            "bEhvc3QuU2Vzc2lvblN0YXRlUmVzcG9uc2UiABJuChFTZW5kTG9nb3V0UmVx",
            "dWVzdBIqLlBvZC5HcnBjLk1lc3NhZ2VzLlNoZWxsSG9zdC5Mb2dvdXRSZXF1",
            "ZXN0GisuUG9kLkdycGMuTWVzc2FnZXMuU2hlbGxIb3N0LkxvZ291dFJlc3Bv",
            "bnNlIgASbwoKRGlzY29ubmVjdBIuLlBvZC5HcnBjLk1lc3NhZ2VzLlNoZWxs",
            "SG9zdC5EaXNjb25uZWN0UmVxdWVzdBovLlBvZC5HcnBjLk1lc3NhZ2VzLlNo",
            "ZWxsSG9zdC5EaXNjb25uZWN0UmVzcG9uc2UiAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Pod.Grpc.Messages.ShellHost.MessagesShellHostReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
