#region Licence
/****************************************************************
 *  Filename: ServiceShellApplications.cs
 *  ----------------------------------------------------------
 *  Author        Martin Meissner
 *  Date          2026-05-19
 *  Copyright (c) 2026 Martin Meissner.
 *                Released under the Apache License 2.0 as part of
 *                the open-source PlayOnDemand release.
 *
 *  SPDX-License-Identifier: Apache-2.0
 ****************************************************************/
#endregion
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ServiceShellApplications.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pod.Grpc.ShellApplications {

  /// <summary>Holder for reflection information generated from ServiceShellApplications.proto</summary>
  public static partial class ServiceShellApplicationsReflection {

    #region Descriptor
    /// <summary>File descriptor for ServiceShellApplications.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceShellApplicationsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5TZXJ2aWNlU2hlbGxBcHBsaWNhdGlvbnMucHJvdG8SGlBvZC5HcnBjLlNo",
            "ZWxsQXBwbGljYXRpb25zGh9NZXNzYWdlc1NoZWxsQXBwbGljYXRpb25zLnBy",
            "b3RvMqwFChtTaGVsbEFwcGxpY2F0aW9uU2VydmljZUdycGMSeQoQR2V0U3lu",
            "Y0FwcFN0YXRlcxIwLlBvZC5HcnBjLk1lc3NhZ2VzLlNoZWxsQXBwbGljYXRp",
            "b25zLlN5bmNSZXF1ZXN0GjEuUG9kLkdycGMuTWVzc2FnZXMuU2hlbGxBcHBs",
            "aWNhdGlvbnMuU3luY1Jlc3BvbnNlIgASggEKEVNlbmRTeW5jQXBwU3RhdGVz",
            "EjQuUG9kLkdycGMuTWVzc2FnZXMuU2hlbGxBcHBsaWNhdGlvbnMuU3luY0Fw",
            "cHNSZXF1ZXN0GjUuUG9kLkdycGMuTWVzc2FnZXMuU2hlbGxBcHBsaWNhdGlv",
            "bnMuU3luY0FwcHNSZXNwb25zZSIAEoMBChBTZW5kQXBwSW5zdGFsbGVkEjgu",
            "UG9kLkdycGMuTWVzc2FnZXMuU2hlbGxBcHBsaWNhdGlvbnMuQXBwSW5zdGFs",
            "bGVkUmVxdWVzdBozLlBvZC5HcnBjLk1lc3NhZ2VzLlNoZWxsQXBwbGljYXRp",
            "b25zLlVwZGF0ZVJlc3BvbnNlIgASfQoNU2VuZEFwcFVwZGF0ZRI1LlBvZC5H",
            "cnBjLk1lc3NhZ2VzLlNoZWxsQXBwbGljYXRpb25zLkFwcFVwZGF0ZVJlcXVl",
            "c3QaMy5Qb2QuR3JwYy5NZXNzYWdlcy5TaGVsbEFwcGxpY2F0aW9ucy5VcGRh",
            "dGVSZXNwb25zZSIAEocBChJTZW5kQXBwVW5pbnN0YWxsZWQSOi5Qb2QuR3Jw",
            "Yy5NZXNzYWdlcy5TaGVsbEFwcGxpY2F0aW9ucy5BcHBVbmluc3RhbGxlZFJl",
            "cXVlc3QaMy5Qb2QuR3JwYy5NZXNzYWdlcy5TaGVsbEFwcGxpY2F0aW9ucy5V",
            "cGRhdGVSZXNwb25zZSIAYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Pod.Grpc.Messages.ShellApplications.MessagesShellApplicationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
