#region Licence
/****************************************************************
 *  Filename: ServiceShellApplicationsGrpc.cs
 *  ----------------------------------------------------------
 *  Author        Martin Meissner
 *  Date          2026-05-19
 *  Copyright (c) 2026 Martin Meissner.
 *                Released under the Apache License 2.0 as part of
 *                the open-source PlayOnDemand release.
 *
 *  SPDX-License-Identifier: Apache-2.0
 ****************************************************************/
#endregion
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ServiceShellApplications.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Pod.Grpc.ShellApplications {
  public static partial class ShellApplicationServiceGrpc
  {
    static readonly string __ServiceName = "Pod.Grpc.ShellApplications.ShellApplicationServiceGrpc";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellApplications.SyncRequest> __Marshaller_Pod_Grpc_Messages_ShellApplications_SyncRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellApplications.SyncRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellApplications.SyncResponse> __Marshaller_Pod_Grpc_Messages_ShellApplications_SyncResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellApplications.SyncResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellApplications.SyncAppsRequest> __Marshaller_Pod_Grpc_Messages_ShellApplications_SyncAppsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellApplications.SyncAppsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellApplications.SyncAppsResponse> __Marshaller_Pod_Grpc_Messages_ShellApplications_SyncAppsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellApplications.SyncAppsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellApplications.AppInstalledRequest> __Marshaller_Pod_Grpc_Messages_ShellApplications_AppInstalledRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellApplications.AppInstalledRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellApplications.UpdateResponse> __Marshaller_Pod_Grpc_Messages_ShellApplications_UpdateResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellApplications.UpdateResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellApplications.AppUpdateRequest> __Marshaller_Pod_Grpc_Messages_ShellApplications_AppUpdateRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellApplications.AppUpdateRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Pod.Grpc.Messages.ShellApplications.AppUninstalledRequest> __Marshaller_Pod_Grpc_Messages_ShellApplications_AppUninstalledRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Pod.Grpc.Messages.ShellApplications.AppUninstalledRequest.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Pod.Grpc.Messages.ShellApplications.SyncRequest, global::Pod.Grpc.Messages.ShellApplications.SyncResponse> __Method_GetSyncAppStates = new grpc::Method<global::Pod.Grpc.Messages.ShellApplications.SyncRequest, global::Pod.Grpc.Messages.ShellApplications.SyncResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetSyncAppStates",
        __Marshaller_Pod_Grpc_Messages_ShellApplications_SyncRequest,
        __Marshaller_Pod_Grpc_Messages_ShellApplications_SyncResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Pod.Grpc.Messages.ShellApplications.SyncAppsRequest, global::Pod.Grpc.Messages.ShellApplications.SyncAppsResponse> __Method_SendSyncAppStates = new grpc::Method<global::Pod.Grpc.Messages.ShellApplications.SyncAppsRequest, global::Pod.Grpc.Messages.ShellApplications.SyncAppsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendSyncAppStates",
        __Marshaller_Pod_Grpc_Messages_ShellApplications_SyncAppsRequest,
        __Marshaller_Pod_Grpc_Messages_ShellApplications_SyncAppsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Pod.Grpc.Messages.ShellApplications.AppInstalledRequest, global::Pod.Grpc.Messages.ShellApplications.UpdateResponse> __Method_SendAppInstalled = new grpc::Method<global::Pod.Grpc.Messages.ShellApplications.AppInstalledRequest, global::Pod.Grpc.Messages.ShellApplications.UpdateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendAppInstalled",
        __Marshaller_Pod_Grpc_Messages_ShellApplications_AppInstalledRequest,
        __Marshaller_Pod_Grpc_Messages_ShellApplications_UpdateResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Pod.Grpc.Messages.ShellApplications.AppUpdateRequest, global::Pod.Grpc.Messages.ShellApplications.UpdateResponse> __Method_SendAppUpdate = new grpc::Method<global::Pod.Grpc.Messages.ShellApplications.AppUpdateRequest, global::Pod.Grpc.Messages.ShellApplications.UpdateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendAppUpdate",
        __Marshaller_Pod_Grpc_Messages_ShellApplications_AppUpdateRequest,
        __Marshaller_Pod_Grpc_Messages_ShellApplications_UpdateResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Pod.Grpc.Messages.ShellApplications.AppUninstalledRequest, global::Pod.Grpc.Messages.ShellApplications.UpdateResponse> __Method_SendAppUninstalled = new grpc::Method<global::Pod.Grpc.Messages.ShellApplications.AppUninstalledRequest, global::Pod.Grpc.Messages.ShellApplications.UpdateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendAppUninstalled",
        __Marshaller_Pod_Grpc_Messages_ShellApplications_AppUninstalledRequest,
        __Marshaller_Pod_Grpc_Messages_ShellApplications_UpdateResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Pod.Grpc.ShellApplications.ServiceShellApplicationsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ShellApplicationServiceGrpc</summary>
    [grpc::BindServiceMethod(typeof(ShellApplicationServiceGrpc), "BindService")]
    public abstract partial class ShellApplicationServiceGrpcBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Pod.Grpc.Messages.ShellApplications.SyncResponse> GetSyncAppStates(global::Pod.Grpc.Messages.ShellApplications.SyncRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Pod.Grpc.Messages.ShellApplications.SyncAppsResponse> SendSyncAppStates(global::Pod.Grpc.Messages.ShellApplications.SyncAppsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Pod.Grpc.Messages.ShellApplications.UpdateResponse> SendAppInstalled(global::Pod.Grpc.Messages.ShellApplications.AppInstalledRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Pod.Grpc.Messages.ShellApplications.UpdateResponse> SendAppUpdate(global::Pod.Grpc.Messages.ShellApplications.AppUpdateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Pod.Grpc.Messages.ShellApplications.UpdateResponse> SendAppUninstalled(global::Pod.Grpc.Messages.ShellApplications.AppUninstalledRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ShellApplicationServiceGrpc</summary>
    public partial class ShellApplicationServiceGrpcClient : grpc::ClientBase<ShellApplicationServiceGrpcClient>
    {
      /// <summary>Creates a new client for ShellApplicationServiceGrpc</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ShellApplicationServiceGrpcClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ShellApplicationServiceGrpc that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ShellApplicationServiceGrpcClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ShellApplicationServiceGrpcClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ShellApplicationServiceGrpcClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellApplications.SyncResponse GetSyncAppStates(global::Pod.Grpc.Messages.ShellApplications.SyncRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSyncAppStates(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellApplications.SyncResponse GetSyncAppStates(global::Pod.Grpc.Messages.ShellApplications.SyncRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetSyncAppStates, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellApplications.SyncResponse> GetSyncAppStatesAsync(global::Pod.Grpc.Messages.ShellApplications.SyncRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSyncAppStatesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellApplications.SyncResponse> GetSyncAppStatesAsync(global::Pod.Grpc.Messages.ShellApplications.SyncRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetSyncAppStates, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellApplications.SyncAppsResponse SendSyncAppStates(global::Pod.Grpc.Messages.ShellApplications.SyncAppsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendSyncAppStates(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellApplications.SyncAppsResponse SendSyncAppStates(global::Pod.Grpc.Messages.ShellApplications.SyncAppsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendSyncAppStates, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellApplications.SyncAppsResponse> SendSyncAppStatesAsync(global::Pod.Grpc.Messages.ShellApplications.SyncAppsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendSyncAppStatesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellApplications.SyncAppsResponse> SendSyncAppStatesAsync(global::Pod.Grpc.Messages.ShellApplications.SyncAppsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendSyncAppStates, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellApplications.UpdateResponse SendAppInstalled(global::Pod.Grpc.Messages.ShellApplications.AppInstalledRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendAppInstalled(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellApplications.UpdateResponse SendAppInstalled(global::Pod.Grpc.Messages.ShellApplications.AppInstalledRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendAppInstalled, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellApplications.UpdateResponse> SendAppInstalledAsync(global::Pod.Grpc.Messages.ShellApplications.AppInstalledRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendAppInstalledAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellApplications.UpdateResponse> SendAppInstalledAsync(global::Pod.Grpc.Messages.ShellApplications.AppInstalledRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendAppInstalled, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellApplications.UpdateResponse SendAppUpdate(global::Pod.Grpc.Messages.ShellApplications.AppUpdateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendAppUpdate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellApplications.UpdateResponse SendAppUpdate(global::Pod.Grpc.Messages.ShellApplications.AppUpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendAppUpdate, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellApplications.UpdateResponse> SendAppUpdateAsync(global::Pod.Grpc.Messages.ShellApplications.AppUpdateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendAppUpdateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellApplications.UpdateResponse> SendAppUpdateAsync(global::Pod.Grpc.Messages.ShellApplications.AppUpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendAppUpdate, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellApplications.UpdateResponse SendAppUninstalled(global::Pod.Grpc.Messages.ShellApplications.AppUninstalledRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendAppUninstalled(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Pod.Grpc.Messages.ShellApplications.UpdateResponse SendAppUninstalled(global::Pod.Grpc.Messages.ShellApplications.AppUninstalledRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendAppUninstalled, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellApplications.UpdateResponse> SendAppUninstalledAsync(global::Pod.Grpc.Messages.ShellApplications.AppUninstalledRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendAppUninstalledAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Pod.Grpc.Messages.ShellApplications.UpdateResponse> SendAppUninstalledAsync(global::Pod.Grpc.Messages.ShellApplications.AppUninstalledRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendAppUninstalled, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ShellApplicationServiceGrpcClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ShellApplicationServiceGrpcClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(ShellApplicationServiceGrpcBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetSyncAppStates, serviceImpl.GetSyncAppStates)
          .AddMethod(__Method_SendSyncAppStates, serviceImpl.SendSyncAppStates)
          .AddMethod(__Method_SendAppInstalled, serviceImpl.SendAppInstalled)
          .AddMethod(__Method_SendAppUpdate, serviceImpl.SendAppUpdate)
          .AddMethod(__Method_SendAppUninstalled, serviceImpl.SendAppUninstalled).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ShellApplicationServiceGrpcBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetSyncAppStates, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Pod.Grpc.Messages.ShellApplications.SyncRequest, global::Pod.Grpc.Messages.ShellApplications.SyncResponse>(serviceImpl.GetSyncAppStates));
      serviceBinder.AddMethod(__Method_SendSyncAppStates, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Pod.Grpc.Messages.ShellApplications.SyncAppsRequest, global::Pod.Grpc.Messages.ShellApplications.SyncAppsResponse>(serviceImpl.SendSyncAppStates));
      serviceBinder.AddMethod(__Method_SendAppInstalled, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Pod.Grpc.Messages.ShellApplications.AppInstalledRequest, global::Pod.Grpc.Messages.ShellApplications.UpdateResponse>(serviceImpl.SendAppInstalled));
      serviceBinder.AddMethod(__Method_SendAppUpdate, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Pod.Grpc.Messages.ShellApplications.AppUpdateRequest, global::Pod.Grpc.Messages.ShellApplications.UpdateResponse>(serviceImpl.SendAppUpdate));
      serviceBinder.AddMethod(__Method_SendAppUninstalled, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Pod.Grpc.Messages.ShellApplications.AppUninstalledRequest, global::Pod.Grpc.Messages.ShellApplications.UpdateResponse>(serviceImpl.SendAppUninstalled));
    }

  }
}
#endregion
