//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeapVR.Content.Creator.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeapVR.Content.Creator.Language.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Main Executable Path.
        /// </summary>
        public static string ApplicationMainExecutablePath {
            get {
                return ResourceManager.GetString("ApplicationMainExecutablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the applixcation main executable file. Usually it is the application executable itself, for some applications requiring an external launcher this should be set the path to the launcher executable file..
        /// </summary>
        public static string ApplicationMainExecutablePath_Instruction {
            get {
                return ResourceManager.GetString("ApplicationMainExecutablePath_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Main Process Name.
        /// </summary>
        public static string ApplicationMainProcessName {
            get {
                return ResourceManager.GetString("ApplicationMainProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application main process name(usually the application executable file name without extension) is used to provide information for the shell to be aware of whether the application is started or not, is it still responding during lifetime and kill the application. Note this should not consider the launcher if there it is..
        /// </summary>
        public static string ApplicationMainProcessName_Instruction {
            get {
                return ResourceManager.GetString("ApplicationMainProcessName_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Process Names.
        /// </summary>
        public static string ApplicationProcessNames {
            get {
                return ResourceManager.GetString("ApplicationProcessNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Besides the application main process name, the application could have multiple different processes running during lifetime. Specify the process names if there are and split them with &quot;;&quot;. This is optional.
        /// </summary>
        public static string ApplicationProcessNames_Instruction {
            get {
                return ResourceManager.GetString("ApplicationProcessNames_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string BasicInfo_SelectLanguage {
            get {
                return ResourceManager.GetString("BasicInfo_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Platform.
        /// </summary>
        public static string BasicInfo_TargetPlatform {
            get {
                return ResourceManager.GetString("BasicInfo_TargetPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Complete_Done {
            get {
                return ResourceManager.GetString("Complete_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Complete_Error {
            get {
                return ResourceManager.GetString("Complete_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VBox Installation Package creation process has encountered a problem. Please check validity of all provided data and try again..
        /// </summary>
        public static string Complete_ErrorMessage {
            get {
                return ResourceManager.GetString("Complete_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique Application ID.
        /// </summary>
        public static string DetailInfo_ApplicationGuid {
            get {
                return ResourceManager.GetString("DetailInfo_ApplicationGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you upload is beyond maximum allowed size: {0}.
        /// </summary>
        public static string DetailInfo_BeyondMaximumFileSizeFormat {
            get {
                return ResourceManager.GetString("DetailInfo_BeyondMaximumFileSizeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string DetailInfo_Category {
            get {
                return ResourceManager.GetString("DetailInfo_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DetailInfo_Description {
            get {
                return ResourceManager.GetString("DetailInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided Executable File Path is not relative to Application Base Directory..
        /// </summary>
        public static string DetailInfo_ExecutablePathNotRelative {
            get {
                return ResourceManager.GetString("DetailInfo_ExecutablePathNotRelative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string DetailInfo_Image {
            get {
                return ResourceManager.GetString("DetailInfo_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Size.
        /// </summary>
        public static string DetailInfo_ImageRecommendedSize {
            get {
                return ResourceManager.GetString("DetailInfo_ImageRecommendedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided picture have invalid dimensions (max allowed is {0}x{0} px).
        /// </summary>
        public static string DetailInfo_InvalidPictureDimensions {
            get {
                return ResourceManager.GetString("DetailInfo_InvalidPictureDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided picture file&apos;s format is invalid..
        /// </summary>
        public static string DetailInfo_InvalidPictureFile {
            get {
                return ResourceManager.GetString("DetailInfo_InvalidPictureFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail Image.
        /// </summary>
        public static string DetailInfo_Thumbnail_Image {
            get {
                return ResourceManager.GetString("DetailInfo_Thumbnail_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string DetailInfo_Title {
            get {
                return ResourceManager.GetString("DetailInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Responding Detection.
        /// </summary>
        public static string EnableRespondingDetection {
            get {
                return ResourceManager.GetString("EnableRespondingDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow the shell to detect application responding and make further decision if it&apos;s not responding..
        /// </summary>
        public static string EnableRespondingDetection_Instruction {
            get {
                return ResourceManager.GetString("EnableRespondingDetection_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Tracking Child Processes.
        /// </summary>
        public static string EnableTrackingChildProcesses {
            get {
                return ResourceManager.GetString("EnableTrackingChildProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow the shell to track processes which are dynamically created since the starting process get executed. It is helpful when there&apos;re unknown amount of processes executed during an application running. However, this will slow the performance a little bit down..
        /// </summary>
        public static string EnableTrackingChildProcesses_Instruction {
            get {
                return ResourceManager.GetString("EnableTrackingChildProcesses_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leap VR.
        /// </summary>
        public static string Enum_Platform_LeapVR {
            get {
                return ResourceManager.GetString("Enum_Platform_LeapVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam.
        /// </summary>
        public static string Enum_Platform_Steam {
            get {
                return ResourceManager.GetString("Enum_Platform_Steam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced settings.
        /// </summary>
        public static string ExecutableInfo_Advanced {
            get {
                return ResourceManager.GetString("ExecutableInfo_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Base Directory.
        /// </summary>
        public static string ExecutableInfo_GameBaseDirectory {
            get {
                return ResourceManager.GetString("ExecutableInfo_GameBaseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The highest directory in directory tree that holds all files and directories needed by the game to run properly..
        /// </summary>
        public static string ExecutableInfo_GameBaseDirectoryInstruction {
            get {
                return ResourceManager.GetString("ExecutableInfo_GameBaseDirectoryInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Executable Parameters.
        /// </summary>
        public static string ExecutableInfo_GameExecutableParameters {
            get {
                return ResourceManager.GetString("ExecutableInfo_GameExecutableParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters that will be provided to the main executable when execution of the game is requested..
        /// </summary>
        public static string ExecutableInfo_GameExecutableParametersInstruction {
            get {
                return ResourceManager.GetString("ExecutableInfo_GameExecutableParametersInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Files.
        /// </summary>
        public static string ExecutableInfo_GameFiles {
            get {
                return ResourceManager.GetString("ExecutableInfo_GameFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executables.
        /// </summary>
        public static string Executables {
            get {
                return ResourceManager.GetString("Executables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Instructions.
        /// </summary>
        public static string ExecutionInstructions {
            get {
                return ResourceManager.GetString("ExecutionInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string FlowControl_Back {
            get {
                return ResourceManager.GetString("FlowControl_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string FlowControl_Create {
            get {
                return ResourceManager.GetString("FlowControl_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string FlowControl_Exit {
            get {
                return ResourceManager.GetString("FlowControl_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string FlowControl_Next {
            get {
                return ResourceManager.GetString("FlowControl_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Global_Browse {
            get {
                return ResourceManager.GetString("Global_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string Global_Browse_AllFiles {
            get {
                return ResourceManager.GetString("Global_Browse_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBox Installation Package.
        /// </summary>
        public static string Global_Browse_Container {
            get {
                return ResourceManager.GetString("Global_Browse_Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable.
        /// </summary>
        public static string Global_Browse_Executable {
            get {
                return ResourceManager.GetString("Global_Browse_Executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files.
        /// </summary>
        public static string Global_Browse_ImageFiles {
            get {
                return ResourceManager.GetString("Global_Browse_ImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Global_Cancel {
            get {
                return ResourceManager.GetString("Global_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container Version.
        /// </summary>
        public static string Global_ContainerVersion {
            get {
                return ResourceManager.GetString("Global_ContainerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Size on Disk.
        /// </summary>
        public static string Global_DiskSizeRequired {
            get {
                return ResourceManager.GetString("Global_DiskSizeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate New ID.
        /// </summary>
        public static string Global_GenerateNewGuid {
            get {
                return ResourceManager.GetString("Global_GenerateNewGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Global_Ok {
            get {
                return ResourceManager.GetString("Global_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBox Installation Package Creator.
        /// </summary>
        public static string Global_ProductName {
            get {
                return ResourceManager.GetString("Global_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Global_Reload {
            get {
                return ResourceManager.GetString("Global_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Directory.
        /// </summary>
        public static string Global_Select_Directory {
            get {
                return ResourceManager.GetString("Global_Select_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string Global_Select_File {
            get {
                return ResourceManager.GetString("Global_Select_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field cannot be left empty..
        /// </summary>
        public static string Global_Validation_CannotBeEmpty {
            get {
                return ResourceManager.GetString("Global_Validation_CannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Global_Warning {
            get {
                return ResourceManager.GetString("Global_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string InstructionName {
            get {
                return ResourceManager.GetString("InstructionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A display name for one executable instruction that infers what&apos;s it about.
        /// </summary>
        public static string InstructionName_Introduction {
            get {
                return ResourceManager.GetString("InstructionName_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Main Executable.
        /// </summary>
        public static string IsMainExecutable {
            get {
                return ResourceManager.GetString("IsMainExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether this executable is one of the executables taken into consideration to check if the application is running. Normally an application requires at least one main executable. Multiple main executables mean any of them running will the application be considered as running..
        /// </summary>
        public static string IsMainExecutable_Introduction {
            get {
                return ResourceManager.GetString("IsMainExecutable_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill On Application Exit.
        /// </summary>
        public static string KillOnExit {
            get {
                return ResourceManager.GetString("KillOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether this process should be killed on application exit.
        /// </summary>
        public static string KillOnExit_Introduction {
            get {
                return ResourceManager.GetString("KillOnExit_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill on Not Responding.
        /// </summary>
        public static string KillProcessIfNotResponding {
            get {
                return ResourceManager.GetString("KillProcessIfNotResponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether this process should be killed when the system detects it is not responding.
        /// </summary>
        public static string KillProcessIfNotResponding_Introduction {
            get {
                return ResourceManager.GetString("KillProcessIfNotResponding_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of added executables is marked as main executable, are you sure to continue?.
        /// </summary>
        public static string NoneExecutableIsMainExecutable {
            get {
                return ResourceManager.GetString("NoneExecutableIsMainExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Monitoring.
        /// </summary>
        public static string ProcessMonitoring {
            get {
                return ResourceManager.GetString("ProcessMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Files.
        /// </summary>
        public static string Progress_CreatingFiles {
            get {
                return ResourceManager.GetString("Progress_CreatingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Progress_Done {
            get {
                return ResourceManager.GetString("Progress_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required VR Module.
        /// </summary>
        public static string RequiredVrModule {
            get {
                return ResourceManager.GetString("RequiredVrModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the corresponding vr module to match the correct graphic api..
        /// </summary>
        public static string RequiredVrModule_Introduction {
            get {
                return ResourceManager.GetString("RequiredVrModule_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set From Exe.
        /// </summary>
        public static string SetFromExecutable {
            get {
                return ResourceManager.GetString("SetFromExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select platform.
        /// </summary>
        public static string Shell_SelectPlatform {
            get {
                return ResourceManager.GetString("Shell_SelectPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Shell_StartCreation {
            get {
                return ResourceManager.GetString("Shell_StartCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Shell_StartEdit {
            get {
                return ResourceManager.GetString("Shell_StartEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBox 2 Zip.
        /// </summary>
        public static string Shell_StartVBoxToZip {
            get {
                return ResourceManager.GetString("Shell_StartVBoxToZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providing SteamID will allow Creator to automatically provide game Title and Image from Steam database..
        /// </summary>
        public static string Shell_SteamIDInstruction {
            get {
                return ResourceManager.GetString("Shell_SteamIDInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam ID (optional).
        /// </summary>
        public static string Shell_SteamIdOptional {
            get {
                return ResourceManager.GetString("Shell_SteamIdOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam ID.
        /// </summary>
        public static string Shell_StemId {
            get {
                return ResourceManager.GetString("Shell_StemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Shell_Tools {
            get {
                return ResourceManager.GetString("Shell_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files Count.
        /// </summary>
        public static string Summary_FileCount {
            get {
                return ResourceManager.GetString("Summary_FileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already exists, are you sure to override the file?.
        /// </summary>
        public static string Summary_Output_FileAlreadyExists {
            get {
                return ResourceManager.GetString("Summary_Output_FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Output Path.
        /// </summary>
        public static string Summary_OutputPackageName {
            get {
                return ResourceManager.GetString("Summary_OutputPackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output path that the installation package will be saved to when creation process is done. The installation package have `.vbox` extension..
        /// </summary>
        public static string Summary_OutputPackageNameInstruction {
            get {
                return ResourceManager.GetString("Summary_OutputPackageNameInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Files Size.
        /// </summary>
        public static string Summary_TotalSize {
            get {
                return ResourceManager.GetString("Summary_TotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Modes.
        /// </summary>
        public static string SupportedModes {
            get {
                return ResourceManager.GetString("SupportedModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured on opening the VBox Package Files. /n Please check if all files are in place and not corrupt. .
        /// </summary>
        public static string Validation_ErrorVBoxPackageOpenEdit {
            get {
                return ResourceManager.GetString("Validation_ErrorVBoxPackageOpenEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character detected in output path, it is replaced with &apos;{0}&apos; and you could adjust it..
        /// </summary>
        public static string Validation_InvalidFilenameCharFormat {
            get {
                return ResourceManager.GetString("Validation_InvalidFilenameCharFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during open VBox Package.
        /// </summary>
        public static string Validation_VBoxPackage_Edit_MsgBox_Error_Caption {
            get {
                return ResourceManager.GetString("Validation_VBoxPackage_Edit_MsgBox_Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watchdog Options.
        /// </summary>
        public static string WatchdogOptions {
            get {
                return ResourceManager.GetString("WatchdogOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Directory.
        /// </summary>
        public static string WorkingDirectory {
            get {
                return ResourceManager.GetString("WorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working directory of a specific executable. If not set, working directory will be set to the directory where the executable is.
        /// </summary>
        public static string WorkingDirectory_Introduction {
            get {
                return ResourceManager.GetString("WorkingDirectory_Introduction", resourceCulture);
            }
        }
    }
}
