//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeapVR.Shell.Categories {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeapVR.Shell.Categories.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D.
        /// </summary>
        public static string Category_2D {
            get {
                return ResourceManager.GetString("Category_2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D.
        /// </summary>
        public static string Category_3D {
            get {
                return ResourceManager.GetString("Category_3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Category_action {
            get {
                return ResourceManager.GetString("Category_action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventure.
        /// </summary>
        public static string Category_adventure {
            get {
                return ResourceManager.GetString("Category_adventure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcade.
        /// </summary>
        public static string Category_arcade {
            get {
                return ResourceManager.GetString("Category_arcade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle.
        /// </summary>
        public static string Category_battle {
            get {
                return ResourceManager.GetString("Category_battle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boardgames.
        /// </summary>
        public static string Category_card {
            get {
                return ResourceManager.GetString("Category_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comic.
        /// </summary>
        public static string Category_cartoon {
            get {
                return ResourceManager.GetString("Category_cartoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casual.
        /// </summary>
        public static string Category_casual {
            get {
                return ResourceManager.GetString("Category_casual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        public static string Category_classic {
            get {
                return ResourceManager.GetString("Category_classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co-Op.
        /// </summary>
        public static string Category_co_op {
            get {
                return ResourceManager.GetString("Category_co_op", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Category_education {
            get {
                return ResourceManager.GetString("Category_education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        public static string Category_explore {
            get {
                return ResourceManager.GetString("Category_explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horror.
        /// </summary>
        public static string Category_horror {
            get {
                return ResourceManager.GetString("Category_horror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string Category_music {
            get {
                return ResourceManager.GetString("Category_music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open World.
        /// </summary>
        public static string Category_open_world {
            get {
                return ResourceManager.GetString("Category_open_world", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        public static string Category_party {
            get {
                return ResourceManager.GetString("Category_party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel.
        /// </summary>
        public static string Category_pixel {
            get {
                return ResourceManager.GetString("Category_pixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puzzle.
        /// </summary>
        public static string Category_puzzle {
            get {
                return ResourceManager.GetString("Category_puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racing.
        /// </summary>
        public static string Category_race {
            get {
                return ResourceManager.GetString("Category_race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Scale.
        /// </summary>
        public static string Category_room_scale {
            get {
                return ResourceManager.GetString("Category_room_scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPG.
        /// </summary>
        public static string Category_rpg {
            get {
                return ResourceManager.GetString("Category_rpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sci-Fi.
        /// </summary>
        public static string Category_scifi {
            get {
                return ResourceManager.GetString("Category_scifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shooter.
        /// </summary>
        public static string Category_shooter {
            get {
                return ResourceManager.GetString("Category_shooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation.
        /// </summary>
        public static string Category_sim {
            get {
                return ResourceManager.GetString("Category_sim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        public static string Category_space {
            get {
                return ResourceManager.GetString("Category_space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        public static string Category_sport {
            get {
                return ResourceManager.GetString("Category_sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy.
        /// </summary>
        public static string Category_strategy {
            get {
                return ResourceManager.GetString("Category_strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tower Defense.
        /// </summary>
        public static string Category_tower_defense {
            get {
                return ResourceManager.GetString("Category_tower_defense", resourceCulture);
            }
        }
    }
}
